DROP TABLE IF EXISTS "user"."token" CASCADE;

DROP TABLE IF EXISTS "user"."core_role" CASCADE;

DROP TABLE IF EXISTS "user"."role" CASCADE;

DROP TABLE IF EXISTS "user"."core" CASCADE;

DROP SCHEMA IF EXISTS "user" CASCADE;
